yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

ignore: |
  **/node_modules/**
  **/.trunk/**

rules:
    trailing-spaces: {}
    key-duplicates: {}
    quoted-strings: {
        quote-type: any,
        required: false
    }