name: Validate Pull Request
# This is the same workflow you'd find in our other submodules. Unlike the rest of the workflows in this repo, this one
# is meant to actually run here, so don't call it from other repos.

on:
  pull_request_target:

jobs:
  validate-pull-request:
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-submodule-pull-request.yml@dev
